

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavbar from "./components/ui/MainNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#006d77' }} className="min-h-screen">
        {/* Full-width navbar */}
        <header className="w-full bg-[#edf6f9] shadow-md">
          <MainNavbar />
        </header>

        {/* Restricted-width content */}
        <main className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
