

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNavbar from "./components/ui/MainNavbar";

import { Aleo } from 'next/font/google'
const aleo = Aleo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: '#2b2c28' }} className={aleo.className}>
        {/* Full-width navbar */}
        <header className="w-full shadow-md">
          <MainNavbar />
        </header>

        {/* Restricted-width content */}
        <main className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
